### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by m2ura** [jcc/blog#101]
Hello, after I upgrated to laravel 5.5 I get this error when trying to update a user, or trying to save any data.

![error](https://user-images.githubusercontent.com/13012135/36951500-3b88e2ec-200d-11e8-95dc-bed35d9f8601.png)

**Comment by jcc** [comment]
emmm... Can you show complete error.

**Comment by m2ura** [comment]
I fixed that one, now I get.

![error2](https://user-images.githubusercontent.com/13012135/36989709-319175da-20ab-11e8-9a2a-596cf24c609a.png)

**Comment by m2ura** [comment]
![error2](https://user-images.githubusercontent.com/13012135/36990789-65e28fb0-20ae-11e8-91f9-d8536f12d42e.png)

**Comment by jcc** [comment]
Error message stating class 'App\Support\Response' not found. You can try to check class 'App\Support\Response'.

**Comment by m2ura** [comment]
I managed to fixed that, Now when I run **npm run watch** I get this error below.

![error](https://user-images.githubusercontent.com/13012135/37114835-259716a6-2252-11e8-869f-58aba4b3b8a9.png)

**Comment by m2ura** [comment]
Fixed it, but still Dashboard is not showing, it only gets home.js, app.css, and app.js. home.css is not showing.

**Comment by jcc** [comment]
Emmm...You can try to clone the newest code. If you upgrade by yourself, you maybe have many problems.

**Comment by m2ura** [comment]
Okay I did that, it's working fine now.
