### ISSUE TITLE
php artisan route:list gives error

### ISSUE THREAD

**Issue by UmarAbdullahi** [jcc/blog#102]
First of all congratulations on making such an amazing blog.

i am trying to locate the link to create new article by using the php artisan route:list command. but i get the error below:
[ErrorException]
  You must set the encryption key going forward to improve the security of this library - see this page for more information https://oauth2.thephpleague.com/v5-security-improvements/

so please what's the link to create articles in localhost. I am signed in as admin

**Comment by jcc** [comment]
What's the link to create article? You can create articles in the dashboard.

**Comment by UmarAbdullahi** [comment]
The articles section of the dashboard is blank, hence my confusion.

**Comment by jcc** [comment]
Can you check your project error log? I find it hard to find the problem.

**Comment by UmarAbdullahi** [comment]
When i goto 127.0.0.1:8000/dashboard/articles/   Here is the error i get from developer tools console:

app.js?id=98fbe7210280b2f88848:58663 [Vue warn]: Cannot find element: #app
warn @ app.js?id=98fbe7210280b2f88848:58663
2app.js?id=98fbe7210280b2f88848:58663 [Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Anonymous>
       <Main> at resources\assets\js\dashboard\Main.vue
         <App> at resources\assets\js\App.vue... (1 recursive calls)
           <Root>

![delete](https://user-images.githubusercontent.com/5554283/37149136-3538eb68-22cd-11e8-978e-fecfae935ea4.jpg)

**Comment by jcc** [comment]
Did you modify the code?

**Comment by UmarAbdullahi** [comment]
I guess i must have modified the code because after cloning reinstalling dependencies its now working. Thanks
