### ISSUE TITLE
baseRepository中的store和save方法

### ISSUE THREAD

**Issue by shubiao-yao** [jcc/blog#103]
为什么baseRepository中的store和save方法要共同存在呢？他们执行的动作是一样的，只保留一个save方法不就行了吗？

**Comment by jcc** [comment]
你调用方法的时候可以有 2 种方式，一种是用 store 直接传需要保存的数据，一种方式是用 save 可以指定 model （而这种用法需要传 2 个参数）。看你自己需求而使用

**Comment by shubiao-yao** [comment]
嗯嗯，感谢回复
