### ISSUE TITLE
BaseRepository方法复用问题

### ISSUE THREAD

**Issue by shubiao-yao** [jcc/blog#106]
如果我想查询一条数据或者多条数据，我有这样一个想法：

在BaseRepository实现show()和index()方法，例如：

public function show(array $where) {
    return $this->model->where($where)->first();
}
public function index(array $where, $perpage) {
     return $this->model->where($where)->paginate($perpage);
}
变量where的话类似：https://laravel.com/docs/5.6/queries#where-clauses
$where = [
['age', '>', 20],
['height', '>', 170],
]

这样的话其它use了BaseRepository的Repository如果想查单条或者多条就不用再单独的写方法了。但是不知道这样写合适吗？请教大神

**Comment by jcc** [comment]
可以这样子的。如果 OK，可提交一个 PR 给我，我最近比较忙，晚回了。

**Comment by shubiao-yao** [comment]
好的，感谢回复
