### ISSUE TITLE
@foreach

### ISSUE THREAD

**Issue by m2ura** [jcc/blog#109]
Hello,

I have modified the category view. I want it to loop images for each category but it give me error.

Parse error: syntax error, unexpected 'endforeach' (T_ENDFOREACH), expecting elseif (T_ELSEIF) or else (T_ELSE) or endif (T_ENDIF) (View: /var/www/laravel/Netcoscan/resources/views/category/show.blade.php).

My view

<section class="houses-section">

    	<div class="auto-container">
        	
	
            <div class="sec-title centered">
            	<div class="title">{{ lang('Category Meta') }}</div>
                <h2>{{ $category->name }}</h2>
                <div class="separator"></div>
            </div>

            <div class="row clearfix">
            	@foreach($articles as $article)
                
                <div class="house-block col-md-4 col-sm-6 col-xs-12">
                	<div class="inner-box">
                    	<div class="image">
				@if($article->page_image)
                        	<img src="{{ $article->page_image }}" alt="{{ $article->slug }}">
				@endif
                            <div class="overlay-box">
                            	<div class="overlay-inner">
                                	<div class="content">
                                    	<h3></h3>
                                    </div>
                                    <a class="purchased" href="{{ url($article->slug) }}">{{ $article->title }}</a>

 @empty
                        <li class="list-group-item">{{ lang('Nothing') }}</li>
                    @endforeach

                                </div>
                            </div>
                        </div>
                    </div>

                </div>

 </section>

**Comment by lb308** [comment]
try this 

`	<div class="auto-container">
    	

        <div class="sec-title centered">
        	<div class="title">{{ lang('Category Meta') }}</div>
            <h2>{{ $category->name }}</h2>
            <div class="separator"></div>
        </div>

        <div class="row clearfix">
        	@foreach($articles as $article)
            
            <div class="house-block col-md-4 col-sm-6 col-xs-12">
            	<div class="inner-box">
                	<div class="image">
			            @if($article->page_image)
                    	<img src="{{ $article->page_image }}" alt="{{ $article->slug }}">
                        @else
                        <div class="overlay-box">
                            <div class="overlay-inner">
                                <div class="content">
                                    <h3></h3>
                                </div>
                                <a class="purchased" href="{{ url($article->slug) }}">{{ $article->title }}</a>
                                 @empty
                                {{ lang('Nothing') }}
                            </div>
                        </div>                        
			             @endif
                    </div>
                </div>
            </div>
            @endforeach`
