### ISSUE TITLE
Issue. Not deleting from database

### ISSUE THREAD

**Issue by GarethCott** [jcc/blog#113]
Hey man. Iv noticed a bug, When i del things from the dashboard eg users, discussions, articles it doesn't del off the database but the categories do?

Am i missing something?

**Comment by jcc** [comment]
Emmm...Can you check your log file? I can't target issue.

**Comment by GarethCott** [comment]
Log file seems fine. There is no error passing.
It del from the application, it just remains in the database. Iv tried editing the code but with no luck. 

The category however del from application and database..

**Comment by jcc** [comment]
Oh, I use the soft delete. You can see the column of the `deleted_at` in the database.

**Comment by GarethCott** [comment]
Silly me. Thank you. Should have just looked into the code more.
