### ISSUE TITLE
前台js疑问，求解惑

### ISSUE THREAD

**Issue by luoxulx** [jcc/blog#117]
我在home.js中写了个function ceshi（alert('ceshi')；）但是在show.blade.php文件中调用这个js函数,console显示未定义函数，请问自定义函数应该放在哪里？

**Comment by jcc** [comment]
写一个 `helpers.js` 然后引入咯。

**Comment by luoxulx** [comment]
![image](https://user-images.githubusercontent.com/35016570/39792120-c13e8bf2-5371-11e8-9417-eab3ebea0bde.png)
那请问我可以直接写在原本就存在的这个help.js文件中吗？

**Comment by jcc** [comment]
嗯，然后要用到的地方 `import` 对应的 `function` 就行

**Comment by luoxulx** [comment]
是在home.js中import吗？还是not defined

**Comment by jcc** [comment]
在你用到的地方 `import`

**Comment by luoxulx** [comment]
感谢，我还有个疑问，我现在想在你的大前提下，在写一个模板，请问可以弄两套前端模板吗

**Comment by jcc** [comment]
看你怎么设计咯，设计好结构，可以的
