### ISSUE TITLE
一直不能访问

### ISSUE THREAD

**Issue by rockmelodies** [jcc/blog#118]
![image](https://user-images.githubusercontent.com/24653177/40093006-e01eacce-58f2-11e8-9a4f-3c8f8bcc33c1.png)

**Comment by jcc** [comment]
是你一直没有编译前端成功吧？

**Comment by rockmelodies** [comment]
npm run dev 来编译的

**Comment by rockmelodies** [comment]
会不会跟 nodejs 版本有关系

**Comment by rockmelodies** [comment]
我用的是 centos7

**Comment by rockmelodies** [comment]
> @ development /home/wwwroot/www.91xx.org
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 68% building modules 484/486 modules 2 active ...x.org/resources/assets/sass/home.scssDEPRECATION WARNING on line 17, column 8 of /home/wwwroot/www.91xx.org/resources/assets/sass/public.scss:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

DEPRECATION WARNING on line 17, column 8 of /home/wwwroot/www.91xx.org/resources/assets/sass/public.scss:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

DEPRECATION WARNING on line 6, column 8 of stdin:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

DEPRECATION WARNING on line 9, column 8 of stdin:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

DEPRECATION WARNING on line 10, column 8 of stdin:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

DEPRECATION WARNING on line 13, column 8 of stdin:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

 69% building modules 508/509 modules 1 active ...xx.org/resources/assets/sass/app.scssDEPRECATION WARNING on line 17, column 8 of /home/wwwroot/www.91xx.org/resources/assets/sass/public.scss:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

DEPRECATION WARNING on line 6, column 8 of stdin:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

DEPRECATION WARNING on line 10, column 8 of stdin:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

 69% building modules 509/510 modules 1 active ...x.org/resources/assets/sass/home.scssDEPRECATION WARNING on line 17, column 8 of /home/wwwroot/www.91xx.org/resources/assets/sass/public.scss:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

DEPRECATION WARNING on line 9, column 8 of stdin:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

DEPRECATION WARNING on line 13, column 8 of stdin:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

 95% emitting

 DONE  Compiled successfully in 23687ms

**Comment by rockmelodies** [comment]
![image](https://user-images.githubusercontent.com/24653177/40094254-79e186ce-58f8-11e8-9544-685db831f637.png)
![Uploading image.png…]()

**Comment by jcc** [comment]
跟版本无关，你可以尝试本地编译后再上传到服务器。

**Comment by rockmelodies** [comment]
我再mac下能用

**Comment by jcc** [comment]
@rockmelodies 在你的截图看不出什么问题，暂无法定位。

**Comment by JL003** [comment]
sass文件中导入了.css文件，把 .css 文件名全部改为sass格式

**Comment by BigTigger4cn** [comment]
@JL003 +1 已测，警告消除
