### ISSUE TITLE
The site doesn't actually load

### ISSUE THREAD

**Issue by ABilenduke** [jcc/blog#119]
I set this project up locally, the home page just constantly loads without ever actually loading anything.

**Comment by jcc** [comment]
Had you complied the front-end code？You can install the project according to the [document](https://manual.pigjian.com/).

**Comment by ABilenduke** [comment]
I followed the documentation. There is no errors or anything, it just keeps spinning but doesn't load anything.

**Comment by jcc** [comment]
Emmm...Can you take some screenshots? I can hardly to locate the problem by your description.

**Comment by ABilenduke** [comment]
Yes, unfortunately I just started work so it won't be for several hours. I really appreciate your help.

**Comment by ABilenduke** [comment]
Sorry, I had a busy week. I restarted my computer and everything is fine. Sorry to bother you with this.
