### ISSUE TITLE
"/discussion" route error exception

### ISSUE THREAD

**Issue by shern91** [jcc/blog#12]
When I logged in as admin, hit the "/discussion" route, this error occur. My OS is Linux Mint, I tried to change folder permission(/storage) but still got the same error.

![discussion](https://cloud.githubusercontent.com/assets/16183843/22699311/12f50d1e-ed92-11e6-8493-ab0604ed5355.png)

BTW, you can reply me in Chinese, because I just installed this OS I haven't figure how to type Chinese in Linux, thanks you for provide this awesome project!

**Comment by shern91** [comment]
Sorry for late reply, I has figure out, If I has one deleted user in my database(softdelete), will cause this error. When I restore that user, there is no error.

**Comment by jcc** [comment]
I did not add the foreign keys to the data table. So you could have the problem when you deleted a user record. You can add the foreign key for the column of `user_id` in disscussion migration before   you run the command of `php artisan migrate`. Thanks for your support.
