### ISSUE TITLE
Discussion form doesn't sent recaptcha response

### ISSUE THREAD

**Issue by ABilenduke** [jcc/blog#127]
The response coming in doesn't contain the recaptcha response. Are the values (i.e. title, tags, content) register some where? How do I add more like the recaptcha response?

**Comment by jcc** [comment]
You can add the recaptcha response when you submit the discussions or comments.

**Comment by jcc** [comment]
You can edit the [file](https://github.com/jcc/blog/blob/master/resources/views/discussion/create.blade.php)

**Comment by ABilenduke** [comment]
I did that, added it to the submit button like the documentation says

`<button
                                    type="submit"
                                    class="btn btn-success float-right g-recaptcha"
                                    onClick="this.form.submit(); this.disabled=true;"
                                    data-size="invisible"
                                    data-sitekey="{{ config('services.recaptcha.key') }}">
                                {{ lang('Create Discussion') }}
                            </button>`

**Comment by ABilenduke** [comment]
But it doesn't submit with the response

**Comment by jcc** [comment]
Emmm...Is there an error message?

**Comment by ABilenduke** [comment]
My bad, I was trying to populate a hidden input with the response but it was just messing everything up.
