### ISSUE TITLE
Dashboard not working without artisan serve

### ISSUE THREAD

**Issue by deathbat7** [jcc/blog#128]
all pages run fine if using php artisan serve, but dashboard pages can not run without artisan serve.
example when I access localhost/blog/public/dashboard
the result is just a blank page without any error

**Comment by jcc** [comment]
Please compile the front-end code at first.

**Comment by deathbat7** [comment]
I think the problem is the same as this,
https://stackoverflow.com/questions/40680707/params-field-is-empty-in-router-push/40681470#40681470
but i am confused how to solve it
// route (in your router file should have "name")
{path: '/ errors', name: 'EXAMPLE', component: ...}

// navigating
this. $ router.push ({
     name: 'EXAMPLE',
     params: {errors: '123'}
});

i am really new with vue.js

**Comment by jcc** [comment]
Do you have an error message?
