### ISSUE TITLE
How to have an array of lang variables

### ISSUE THREAD

**Issue by ABilenduke** [jcc/blog#130]
I created an array of variables in the blog lang file i.e.:

```
'stuff' => [
    'morestuff' => 'test',
    'evenmorestuff' => 'test',
]
```

But I can't seem to get it to work, how does the lang function work to retrieve something like that?

**Comment by jcc** [comment]
@ABilenduke `trans('blog.stuff.morestuff')`. If you want to use in the dashboard, You should add the variables to `resources/js/lang`
