### ISSUE TITLE
The Mix manifest does not exist. Shared hosting

### ISSUE THREAD

**Issue by m2ura** [jcc/blog#134]
Hello, I am having a mix manifest error  when deploying into a shared host.

![image](https://user-images.githubusercontent.com/13012135/44241685-c7f2af80-a1c5-11e8-9a74-679912874226.png)

![image](https://user-images.githubusercontent.com/13012135/44241694-d771f880-a1c5-11e8-8c26-bb1b9a2517d0.png)

![image](https://user-images.githubusercontent.com/13012135/44241714-efe21300-a1c5-11e8-8b88-51af60d797fb.png)

Can you please help, what should I do?

**Comment by jcc** [comment]
https://github.com/JeffreyWay/laravel-mix/issues/1352#issuecomment-378125120
