### ISSUE TITLE
我的数据库密码怎么不对, 可以连接的,也可以进去, 但是进入到首页就报这个错?

### ISSUE THREAD

**Issue by jianwoo** [jcc/blog#136]
SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) (SQL: select count(*) as aggregate from `articles` where `articles`.`deleted_at` is null and `is_draft` = 0)

**Comment by jcc** [comment]
拒绝访问，请检查 `.env` 文件
