### ISSUE TITLE
我需要重新建表吗

### ISSUE THREAD

**Issue by jianwoo** [jcc/blog#138]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'blog.articles' doesn't exist (SQL: select count(*) as aggregate from `articles` where `articles`.`deleted_at` is null and `is_draft` = 0)

**Comment by jcc** [comment]
报错显示，没找到 articles 这个表

**Comment by jianwoo** [comment]
正常我迁移成功就可以吧?  😓

**Comment by jianwoo** [comment]
hhly:blog Ng$ php artisan migrate

In Connection.php line 664:
                                                                               
  SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_s  
  chema.tables where table_schema = homestead and table_name = migrations)     
                                                                               

In Connector.php line 68:
                                             
  SQLSTATE[HY000] [2002] Connection refused  
                                             
数据库出现这个报错
