### ISSUE TITLE
Can't get list of my follower's

### ISSUE THREAD

**Issue by vjaykoogu** [jcc/blog#14]
Currently i can check only people i'm Following from my profile. There should be a link where i can check people  those are following me. 

 #eg:
![vijay koogu vijaykoogu on bloglovin followers](https://cloud.githubusercontent.com/assets/87112/22852093/396e9278-f05b-11e6-9550-837eab9dbcc3.png)

**Comment by jcc** [comment]
Yes. How do you do for it? The default's blog had not finished this feature. But you can get the data by the method of `followers` in `app\Traits\FollowTrait`. Can you get the followers by this way?

**Comment by vjaykoogu** [comment]
i'll check this out... Well im trying to understand the code first, so i don't repeat anything.
