### ISSUE TITLE
Article image

### ISSUE THREAD

**Issue by m2ura** [jcc/blog#140]
Hello, 

When posting an article image it doesn't show on a live server... the article gets posted but the image doesn't show. It does show that it's on storage/cover...

<div class="post__image">
<a href="http:///kitchen-design-gvvvc">
<img alt="kitchen-design-gvvvc" src="http://IP_Address/storage/cover/2018/09/09/jxkkUelRsUYem0MXXUVo56IeQ3pwtvsYUm1F34dk.jpg" data-holder-rendered="true">
</a>
</div>

**Comment by jcc** [comment]
emmm...You check if the public directory has a storage folder.
