### ISSUE TITLE
js问题

### ISSUE THREAD

**Issue by luoxulx** [jcc/blog#141]
![image](https://user-images.githubusercontent.com/35016570/45465862-bf03e800-b749-11e8-8766-cf5ba7bd3c61.png)

只有首页能进，点其它菜单均出现如图所示错误（按照文档步骤来的）

**Comment by jcc** [comment]
你的是下载什么版本？

**Comment by luoxulx** [comment]
![image](https://user-images.githubusercontent.com/35016570/45466470-a2b57a80-b74c-11e8-9f3a-18a3a87a53d9.png)

**Comment by jcc** [comment]
试一下将 `webpack.mix.js` 下：
```javascript
themes.forEach((item) => {
  mix.sass(item, 'public/css/themes').version()
})
```
改为：
```javascript
themes.forEach((item) => {
  mix.sass(item, 'public/css/themes')
})
```

**Comment by jcc** [comment]
@luoxulx 更新一下最新版，webpack 配置有点问题，修复了。
