### ISSUE TITLE
npm install 报错了 请问是什么原因

### ISSUE THREAD

**Issue by SoupT** [jcc/blog#143]
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-93-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/html/blog
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm http 304 https://registry.npmjs.org/popper.js
npm http 304 https://registry.npmjs.org/simplemde
npm http 304 https://registry.npmjs.org/social-share.js
npm http 304 https://registry.npmjs.org/sweetalert2
npm http 304 https://registry.npmjs.org/toastr
npm http 304 https://registry.npmjs.org/vue
npm http 304 https://registry.npmjs.org/v-textcomplete
npm http 304 https://registry.npmjs.org/vue-multiselect
npm http 304 https://registry.npmjs.org/vue-router
npm http 304 https://registry.npmjs.org/vuex
npm http 304 https://registry.npmjs.org/vue-datepicker
npm http 200 https://registry.npmjs.org/vue-i18n/6.0.0-alpha.5
npm http GET https://registry.npmjs.org/vue-i18n/-/vue-i18n-6.0.0-alpha.5.tgz
npm http 200 https://registry.npmjs.org/vue-i18n/-/vue-i18n-6.0.0-alpha.5.tgz
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/html/blog/npm-debug.log
npm ERR! not ok code 0

阿里云 ubuntu14.04
node -v v0.10.25
npm -v 1.3.10

**Comment by jcc** [comment]
@SoupT node 和 npm 版本问题

**Comment by gopal-g** [comment]
What should be the node and npm versions ?
