### ISSUE TITLE
fresh install: "There is no permission named `list_category` for guard `web`."

### ISSUE THREAD

**Issue by SamDeacon** [jcc/blog#147]
https://ibb.co/ef8eRL
```
{message: "There is no permission named `list_category` for guard `web`.",…}
exception: "Spatie\Permission\Exceptions\PermissionDoesNotExist"
file: "/Users/samdeacon/Sites/jccblog/vendor/spatie/laravel-permission/src/Exceptions/PermissionDoesNotExist.php"
line: 11
message: "There is no permission named `list_category` for guard `web`."
```

For some reason there is an issue with the backend api routes / permission

I ran the install, logged in with admin and seeder, but the categories / articles api views/components don't workin due to guard / permission

weird because I see it in

resources/lang/en/permissions.php

**Comment by jcc** [comment]
@SamDeacon You need run the command of `php artisan db:seed --class=PermissionTableSeeder`

**Comment by shijunti19** [comment]
@jcc  你这个安装说明到底哪里有完整的，一个个都得搜，我们不关心laravel怎么安装的
