### ISSUE TITLE
Change language and color

### ISSUE THREAD

**Issue by covecove1** [jcc/blog#15]
Hi, 

Can You tell me where I can change language of control panel items like Articles, Tags etc.?
I also don't know where to change color of view elements like navbar?

Thanks

**Comment by jcc** [comment]
You can know more about it in the [manual](https://manual.pigjian.com/en/config.html). But the color of the navbar can't be change now, you must change the color in the file of `variables.scss`. I will think of the feature of change the color for something in the next version. Of course, you also pull a request for the feature to become a contributor what be interesting for you.
