### ISSUE TITLE
不是很好用啊

### ISSUE THREAD

**Issue by shijunti19** [jcc/blog#150]
分类应该在文章创建里支持回车输入啊，标签也是
后台我建议用element
文章编辑器可以用这个https://github.com/hinesboy/mavonEditor支持图片上传
时间可以空就立即发布
有道翻译api设置错误，不返回错误，查了我半天，另外我不知道去哪申请，官方换新网站了！
rss，网站地图后期打算加入吗
我觉得创新的话，最好做个文章第三方对接接口，让我们可以在其他接口里输入创建文章，

**Comment by jcc** [comment]
@shijunti19 自己可以根据自己的需求更改优化。
