### ISSUE TITLE
Post 500 Internal server error

### ISSUE THREAD

**Issue by m2ura** [jcc/blog#157]
Hello,
 I get this when trying to post anything

[2019-01-15 15:36:02] local.ERROR: Key path "file:///var/www/laravel/netcoscan/storage/oauth-public.key" does not exist or is not readable {"exception":"[object] (LogicException(code: 0): Key path \"file:///var/www/laravel/netcoscan/storage/oauth-public.key\" does not exist or is not readable at /var/www/laravel/netcoscan/vendor/league/oauth2-server/src/CryptKey.php:44)
[stacktrace]
#0 /var/www/laravel/netcoscan/vendor/league/oauth2-server/src/ResourceServer.php(50): League\\OAuth2\\Server\\CryptKey->__construct('file:///var/www...')
#1 /var/www/laravel/netcoscan/vendor/laravel/passport/src/PassportServiceProvider.php(217): League\\OAuth2\\Server\\ResourceServer->__construct(Object(Laravel\\Passport\\Bridge\\AccessTokenRepository), 'file:///var/www...')
#2 /var/www/laravel/netcoscan/vendor/laravel/framework/src/Illuminate/Container/Container.php(749): Laravel\\Passport\\PassportServiceProvider->Laravel\\Passport\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#3 /var/www/laravel/netcoscan/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\\Container\\Container->build(Object(Closure))
#4 /var/www/laravel/netcoscan/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\\Container\\Container->resolve('League\\\\OAuth2\\\\S...', Array)
#5 /var/www/laravel/netcoscan/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(721): Illuminate\\Container\\Container->make('League\\\\OAuth2\\\\S...', Array)
#6 /var/www/laravel/netcoscan/vendor/laravel/passport/src/PassportServiceProvider.php(246): Illuminate\\Foundation\\Application->make('League\\\\OAuth2\\\\S...')
#7 [internal function]: Laravel\\Passport\\PassportServiceProvider->Laravel\\Passport\\{closure}(Object(Illuminate\\Http\\Request), NULL)
#8 /var/www/laravel/netcoscan/vendor/laravel/framework/src/Illuminate/Auth/RequestGuard.php(58): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request), NULL)
#9 /var/www/laravel/netcoscan/vendor/laravel/framework/src/Illuminate/Auth/GuardHelpers.php(50): Illuminate\\Auth\\RequestGuard->user()

**Comment by jcc** [comment]
You can run the command of `php artisan passport:install`

**Comment by ziymed** [comment]
Please run this command : 
`php artisan passport:install`

**Comment by m2ura** [comment]
Okay now I get the below when running npm install/npm install --verbose

npm ERR! code E405
npm ERR! 405 Method Not Allowed - GET http://registry.npmjs.org/lodash._root%202207/axios/axios
npm verb exit [ 1, true ]
npm timing npm Completed in 9874ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/offensive/.npm/_logs/2019-01-19T08_16_14_517Z-debug.log


I use the latest Nodejs and npm
npm verb node v10.15.0
npm verb npm  v6.6.0
