### ISSUE TITLE
401 {"error":"Unauthenticated."}

### ISSUE THREAD

**Issue by WenHou** [jcc/blog#158]
可以登录，可以进入 dashboard和个人主页进行所有查看操作，但是所有的 post 请求都401错误，例如上传头像、添加分类、添加 tag 等

**Comment by WenHou** [comment]
重新登录，清理缓存，重启 nginx，重启 PHP，重新编译，日志都尝试过了

**Comment by WenHou** [comment]
![wechatworkscreenshot_a156aea0-6e72-4de3-a639-656535390b8d](https://user-images.githubusercontent.com/6669061/51369655-5aa9c880-1b2f-11e9-8351-29f3424a1cf6.png)
sorry，get 请求也有401

**Comment by WenHou** [comment]
登录成功后 oauth_access_tokens 表没有数据

**Comment by jcc** [comment]
执行一下 `php artisan passport:install`

**Comment by WenHou** [comment]
@jcc  这个也执行过的
