### ISSUE TITLE
.ajaxForm is not a function

### ISSUE THREAD

**Issue by DeeJaVu** [jcc/blog#16]
in user profile when i try to upload an avatar i get this javascript error

Uncaught TypeError: $(...).ajaxForm is not a function

**Comment by jcc** [comment]
Yes, I also find this problem. I will fix it.

**Comment by jcc** [comment]
@DeeJaVu Did you solved the problem?

**Comment by jcc** [comment]
I code the component of the `AvatarUpload.vue` for upload the user avatar to instead of the `Jcrop` in the version of `v1.1.2`.   Thanks for your support.
