### ISSUE TITLE
Getting 401 {"error":"Unauthenticated."} for admin dashboard repeatedly

### ISSUE THREAD

**Issue by ekordev** [jcc/blog#161]
Every couple of days I get the 401 error and nothing resolves the issue other than re-installing from scratch I've followed the steps you suggested here #https://github.com/jcc/blog/issues/158#issue-400591508 with no luck. I have only modified the views and usercontroller.php and the index.php in the public folder.

everything works fine for a few days but when I do get the error I try php artisan passport:install and it says they are already installed

**Comment by jcc** [comment]
Can you show me the error log?

**Comment by ekordev** [comment]
I'm having trouble trying to reproduce the issue on my local machine, and
like I said the error happens randomly but when it does I'm able to revert
to a backup and here's the full log from the backup pastebin
<https://pastebin.com/Zi04ay13>

On Feb 19, 2019 5:24 PM, "Jiajian Chan" <notifications@github.com> wrote:

Can you show me the error log?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jcc/blog/issues/161#issuecomment-465380706>, or mute
the thread

**Comment by ekordev** [comment]
It just happened on my live server, here's the error

Failed to load resource: the server responded with a status of 401 ()
home:1 Uncaught (in promise)

   1. Object
      1. config: {adapter: ƒ, transformRequest: {…}, transformResponse: {…}
      , timeout: 0, xsrfCookieName: "XSRF-TOKEN", …}
      2. data: {error: "Unauthenticated."}
      3. headers: {date: "Wed, 20 Feb 2019 05:12:19 GMT", server:
      "openresty", x-powered-by: "PHP/7.2.13", x-ratelimit-remaining: "58",
      content-type: "application/json", …}
      4. request: XMLHttpRequest
         1. onabort: null
         2. onerror: ƒ ()
         3. onload: null
         4. onloadend: null
         5. onloadstart: null
         6. onprogress: null
         7. onreadystatechange: ƒ ()
         8. ontimeout: ƒ ()
         9. readyState: 4
         10. response: "{"error":"Unauthenticated."}"
         11. responseText: "{"error":"Unauthenticated."}"
         12. responseType: ""
         13. responseURL: "https://checkon.tech/api/statistics"
         14. responseXML: null
         15. status: 401
         16. statusText: ""
         17. timeout: 0
         18. upload: XMLHttpRequestUpload {onloadstart: null, onprogress:
         null, onabort: null, onerror: null, onload: null, …}
         19. withCredentials: false
         20. __proto__: XMLHttpRequest
      5. status: 401
      6. statusText: ""
      7. __proto__:
         1. constructor: ƒ Object()
         2. hasOwnProperty: ƒ hasOwnProperty()
         3. isPrototypeOf: ƒ isPrototypeOf()
         4. propertyIsEnumerable: ƒ propertyIsEnumerable()
         5. toLocaleString: ƒ toLocaleString()
         6. toString: ƒ toString()
         7. valueOf: ƒ valueOf()
         8. __defineGetter__: ƒ __defineGetter__()
         9. __defineSetter__: ƒ __defineSetter__()
         10. __lookupGetter__: ƒ __lookupGetter__()
         11. __lookupSetter__: ƒ __lookupSetter__()
         12. get __proto__: ƒ __proto__()
         13. set __proto__: ƒ __proto__()

**Comment by ekordev** [comment]
I moved from a shared host to a vps after learning that alot of php functions were disabled and haven't had this issue since. Closing for now.
