### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by fnoopv** [jcc/blog#162]
刚拉取了最新的81d3a0c版本代码，执行npm run dev 时报错，主要错误代码如下
` ERROR  Failed to compile with 1 errors                                 23:57:39

This relative module was not found:

* ../../../../node_modules/chart.js/src/chart in ./node_modules/_babel-loader@8.0.5@babel-loader/lib??ref--4-0!./node_modules/_vue-loader@15.7.0@vue-loader/lib??vue-loader-options!./resources/js/home/components/Chartjs.vue?vue&type=script&lang=js&
.............................................
ERROR in ./resources/js/home/components/Chartjs.vue?vue&type=script&lang=js& (./node_modules/_babel-loader@8.0.5@babel-loader/lib??ref--4-0!./node_modules/_vue-loader@15.7.0@vue-loader/lib??vue-loader-options!./resources/js/home/components/Chartjs.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve '../../../../node_modules/chart.js/src/chart' in '/home/fnoop/Desktop/php/blog/resources/js/home/components'
`
然后看了一下resources/js/home/components/Chartjs.vue的代码,发现引用了chart.js,
`import Chart from '../../../../node_modules/chart.js/src/chart'`
然后翻了一下node_modules，发现chart.js目录下面没有src目录，只有dist和node_modules两个目录,然后我把导入路径改为`import Chart from '../../../../node_modules/chart.js/dist/Chart.js'`就不报错，顺利编译通过了

**Comment by daydevelops** [comment]
In resources/js/home/components/Chartjs.vue, you can change the import directory on line 6 to this:

import Chart from '../../../../node_modules/chart.js/dist/Chart.js'

The current import directory was causing the error and this fix removed the error for me.

**Comment by jcc** [comment]
Try to edit the file of Chartjs.vue in 6 line.
Before
```
import Chart from '../../../../node_modules/chart.js/dist/Chart.js'
```
After
```
import Chart from 'chart.js/dist/Chart.js'
```
