### ISSUE TITLE
there is exception when run "php artisan blog:install"

### ISSUE THREAD

**Issue by handyson** [jcc/blog#174]
there is exception when run **"php artisan blog:install"**

`Illuminate\Database\QueryException  : SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'tempore' for key 'tags_tag_unique'`

add a function all **"unique()"** at  \database\factories\ModelFactory.php:line 62 to fix this.

**Comment by yezihack** [comment]
你把app/Console/Commands/BlogInstall.php p39行 改成如下代码
`$this->execShellWithPrettyPrint('php artisan migrate:refresh --seed');`

**Comment by handyson** [comment]
> 你把app/Console/Commands/BlogInstall.php p39行 改成如下代码
> `$this->execShellWithPrettyPrint('php artisan migrate:refresh --seed');`

可以了
