### ISSUE TITLE
An error occurs when executing `composer create-project jcc/blog`. The .env file has existed. The problem is "APP_NAME=PJ Blog".

### ISSUE THREAD

**Issue by Sky-Zeng** [jcc/blog#183]
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
The environment file is invalid!
Failed to parse dotenv file due to unexpected whitespace. Failed at [PJ Blog].
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

**Comment by daydevelops** [comment]
I believe this was fixed with commit [eb57a57](https://github.com/jcc/blog/pull/168/commits/eb57a5742dcaf5cafb194577c355132a701aafba)
