### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by m2ura** [jcc/blog#19]
I don't know if it's me or but after making the recent changes you did, my admin dashboard just don't show up. Everything else does show but the admin panel, all i see is a blank white page..

**Comment by jcc** [comment]
Did you complied the code after changing the *.vue files or *.scss files? I don't know that what happened. But everything is fine on my computer.

**Comment by m2ura** [comment]
Hello, sorry... I managed to fix it... Had a missing code on app.f0bf3309ffd3a589842d.js
