### ISSUE TITLE
默认管理员账号密码

### ISSUE THREAD

**Issue by Sky-Zeng** [jcc/blog#190]
如果有运行过 php artisan blog:install 的命令，那么默认管理员账号是 admin@pigjian.com ，密码是 admin。

**Comment by Sky-Zeng** [comment]
php artisan blog:admin生成的管理员账号可以进入后台，但没有查看和编辑文章等权限。

**Comment by KitchenLiang** [comment]
要id为1才可以查看和编辑文章，新建的看不了，把原来的删了，把新建id设置为1就可以了
