### ISSUE TITLE
Undefined property: App\Http\Controllers\UserController::$user

### ISSUE THREAD

**Issue by vitorhenriquemaia** [jcc/blog#205]
Please, I'm getting this error. I would like to ask for a hand.

public function doFollow($id)
    {
        $user = $this->user->getById($id);        

        if (Auth::user()->isFollowing($id)) {
            Auth::user()->unfollow($id);
        } else {
            Auth::user()->follow($id);

            $user->notify(new FollowedUser(Auth::user()));
        }

        return redirect()->back();
    }

**Comment by markaguilar** [comment]
same error
