### ISSUE TITLE
Cant find where to create posts

### ISSUE THREAD

**Issue by jackpeters667** [jcc/blog#211]
I made an admin account but in my dashboard, I cant click Users, Articles, Views, Comments... they are all unclickable. If i try to go to /dashboard/articles while logged in as an admin, I get a notification saying I dont have the right permissions.. Where do I go to create posts? I attached a screenshot of what I see when I open dashboard
![error](https://user-images.githubusercontent.com/47973728/89241876-6620ef80-d600-11ea-9c7e-a4deb7a878a5.png)

**Comment by jackpeters667** [comment]
![error](https://user-images.githubusercontent.com/47973728/89241751-0e828400-d600-11ea-898c-a867e4a3c3a2.png)

Here's what I see when I open the dashboard

**Comment by jcc** [comment]
Please set the super admin for your account. You can set `APP_SUPER_ADMIN=${Your Account Id}` in .env file.

**Comment by jackpeters667** [comment]
Thank you. Sorry, is that the account ID from the database (the int value)? So for instance in the screen I attached, I add `APP_SUPER_ADMIN=${12}` in then `.env` file?
![id](https://user-images.githubusercontent.com/47973728/89290354-0acf1b80-d659-11ea-83f1-8fb4c32bf489.png)

**Comment by jcc** [comment]
Yes.

**Comment by ed-mor** [comment]
It is without the grouping signs {}, it is simply the id.  For Example:  APP_SUPER_ADMIN=12

**Comment by jackpeters667** [comment]
Perfect. Thank you. I'm trying it out soon. I don't know if it was an obvious fix but could we add that to the basic setup documentation?

**Comment by jackpeters667** [comment]
> It is without the grouping signs {}, it is simply the id. For Example: APP_SUPER_ADMIN=12

Thank you. Working perfectly

**Comment by ed-mor** [comment]
Present it as a pull request. Edit the Readme in a branch and possibly use it.
