### ISSUE TITLE
Call to undefined function snake_case() (View: C:\xampp\htdocs\blog\resources\views\user\notifications.blade.php)

### ISSUE THREAD

**Issue by markaguilar** [jcc/blog#212]

**Comment by akberdiyev** [comment]
I also have this error. Can be linked to the notification->data email_notify_enabled table?

**Comment by akberdiyev** [comment]
I also have this error

**Comment by akberdiyev** [comment]
You must configure smtp on the local server?

**Comment by akberdiyev** [comment]
@include('notifications.'. Str::snake(class_basename($notification->type), '-'))
it helped me
