### ISSUE TITLE
Avatar Upload

### ISSUE THREAD

**Issue by m2ura** [jcc/blog#24]
Hello, I've pulled the latest version that uses the AvatarUpload.vue but still i have the  avatar upload issue, but it does upload the images into the public path uploads/avatar  it's just it doesn't change from default avatar into a new uploaded avatar... I uploaded a screen shot of the issue so you can see because i get this... http://127.0.0.1:8000/user/profile/1 with a response status code 302, it seems like it does Post but doesn't return anything. 

2) How do I change timezones, every time I create an article it's like 1 and a half hour ahead my timezone?

![imageupload](https://cloud.githubusercontent.com/assets/13012135/23379122/6333a37e-fd3e-11e6-8f4c-31e9ce90ff61.png)

Please help, Thank you.

**Comment by jcc** [comment]
I re-clone a new project for test, but I can't reproduce this problem. You can try to check permissions and make sure you clone the latest code with the `master` branch or `v1.1.6`. And then you can edit the `config/app.php` file for changing if you want to change the timezones.
