### ISSUE TITLE
Article Page Image 

### ISSUE THREAD

**Issue by m2ura** [jcc/blog#25]
Plus is there another way to select a page image without actually typing an image path like 'images/image.jpg' maybe to use a button to select a path of a page image from a device/computer storage just in case of an end user?

![page image](https://cloud.githubusercontent.com/assets/13012135/23382369/8e7cc1a8-fd4a-11e6-873a-ead42c222cfc.png)

I am sorry if I am bothering you Sir, this a a great project that you have.

**Comment by jcc** [comment]
I had planned to the feature in the feture. But I have enough time to finish it now. If you want to finish the feture, you also can pull requests.

**Comment by m2ura** [comment]
Cool bro.
