### ISSUE TITLE
Dashboard not work

### ISSUE THREAD

**Issue by zhongjixiuxing** [jcc/blog#26]
我在部署成功后使用admin登陆进入，入到dashboard界面显示是空白的页面， 我运行的dev环境；使用的是chrome 浏览器，控制台上显示的错误信息如下： 
![image](https://cloud.githubusercontent.com/assets/8935235/23393755/03feec24-fdc0-11e6-858b-84b0b11f8282.png)

**Comment by jcc** [comment]
你渲染的时候出问题了，如果你不修改前端则不需要渲染。

**Comment by zhongjixiuxing** [comment]
我目前没有修改过任何的页面

**Comment by jcc** [comment]
@zhongjixiuxing 那你可以不运行 `npm run dev`

**Comment by zhongjixiuxing** [comment]
@jcc 运行 npm run dev 是没问题的，我怀疑时vue的版本问题，我的vue是最新的2.2.1

**Comment by jcc** [comment]
我升级了，也没有出现你所说的问题。
