### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by m2ura** [jcc/blog#27]
Need your help... am I missing something on AvatarUpload.js? because when I click on okay button nothing really happens. When i set crop = false then try to upload avatar it just send the avatar into the storage and not the database. I used your latest release  v1.1.6 

![screenshot from 2017-03-03 00-19-30](https://cloud.githubusercontent.com/assets/13012135/23529782/8accd124-ffa7-11e6-8b6a-00b3e2495aa7.png)
![screenshot from 2017-03-03 01-02-22](https://cloud.githubusercontent.com/assets/13012135/23531143/a6535a20-ffad-11e6-862b-6defa495fe01.png)

**Comment by jcc** [comment]
Oh, The feature of the crop had be removed. If you want to use it, you must code the api for saving the cropped image. And you upload avatar it just send the avatar into the storage and not the database? Can you see the column of the user's avatar had changed in the database?

**Comment by m2ura** [comment]
In the database it's stay as null but in the storage i have avatars, in the User column everything changes except the avatar.

![screenshot from 2017-03-03 09-01-53](https://cloud.githubusercontent.com/assets/13012135/23541482/43602112-fff0-11e6-8082-e4190aacb33c.png)

**Comment by m2ura** [comment]
This are the images I've been selecting for updating avatar but the don't get sent into the database.

**Comment by jcc** [comment]
Now, you try to trace the error. You check the api whether there is an error. And then check the file of `laravel.log`. I believe it can't be save with the error.

**Comment by m2ura** [comment]
Laravel.log there is this error with image intervention

[2017-03-03 08:59:21] local.ERROR: Intervention\Image\Exception\NotReadableException: Unable to init from given url (http://127.0.0.1:8000/uploads/avatar/1/1_1488524240_YM1c8dpZFyJk.jpg). in /var/www/laravel/Sylvester-Blog/vendor/intervention/image/src/Intervention/Image/AbstractDecoder.php:68
Stack trace:
#0 /var/www/laravel/Sylvester-Blog/vendor/intervention/image/src/Intervention/Image/AbstractDecoder.php(308): Intervention\Image\AbstractDecoder->initFromUrl('http://127.0.0....')
#1 /var/www/laravel/Sylvester-Blog/vendor/intervention/image/src/Intervention/Image/AbstractDriver.php(64): Intervention\Image\AbstractDecoder->init('http://127.0.0....')
#2 /var/www/laravel/Sylvester-Blog/vendor/intervention/image/src/Intervention/Image/ImageManager.php(50): Intervention\Image\AbstractDriver->init('http://127.0.0....')
#3 /var/www/laravel/Sylvester-Blog/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Intervention\Image\ImageManager->make('http://127.0.0....')

**Comment by jcc** [comment]
Yes. 'Unable to init from given url', You try to set a domain for the project to instead of `127.0.0.1:8000`

**Comment by m2ura** [comment]
Okay, so i won't be able to upload while I'm using localhost?

**Comment by jcc** [comment]
Yes, the image intervention crop the image through the picture url after uploading. And then the package can't init from given url.

**Comment by jcc** [comment]
@m2ura I had updated the uploader for avatar in the latest version. #28

**Comment by m2ura** [comment]
Thanks bro, I forgot to tell you that It is working now with your previous version. Keep up the great work!!
