### ISSUE TITLE
The parameter app_id is required

### ISSUE THREAD

**Issue by m2ura** [jcc/blog#33]
It's not an issues with your app but I wanna know what could be the possible issue with this error because i do have app_id on my .env file and on my services.php file.

![screenshot from 2017-03-09 15-06-47](https://cloud.githubusercontent.com/assets/13012135/23751535/7fd10aa0-04da-11e7-88ec-1ab67ad7fab3.png)

**Comment by jcc** [comment]
You can try to dump your data to see. May be lost during operation.

**Comment by m2ura** [comment]
When i check on the developer tools this is what i see...

![screenshot from 2017-03-09 15-15-39](https://cloud.githubusercontent.com/assets/13012135/23751770/6f1976a6-04db-11e7-8a5b-13132546843c.png)

**Comment by jcc** [comment]
Oh, You should look at that response page, what data to return.

**Comment by m2ura** [comment]
The response
![screenshot from 2017-03-09 15-23-00](https://cloud.githubusercontent.com/assets/13012135/23752013/5ad697ea-04dc-11e7-9fa4-97799c07a0da.png)

**Comment by jcc** [comment]
You print the data before the trigger authorization, the error is obvious.
