### ISSUE TITLE
public/.htaccess 问题

### ISSUE THREAD

**Issue by smelike** [jcc/blog#34]
安装后，点击“login”，出现 404 页面内。

修改原来的 .htaccess 如下：

>  
    # Redirect Trailing Slashes If Not A Folder...
    # RewriteCond %{REQUEST_FILENAME} !-d
    # RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php/$1 [L]

点击 login 都是 404，只有在 url 后面添加 index.php，才可以看到页面。不过，样式与 JavaScript 文件都包含不进来了。我觉得你的这个项目并没有什么作用。

**Comment by jcc** [comment]
请你看一下 Laravel 服务器配置文档。你的 Apache 需要开启重写模块。

**Comment by smelike** [comment]
重写模块已经开启

2017-03-14 13:41 GMT+08:00 Jiajian Chan <notifications@github.com>:

**Comment by jcc** [comment]
@smelike 很明显，你不会配置 Laravel 的环境，你的 Apache 配置需要指向 public 目录。
