### ISSUE TITLE
ErrorException in CategoryController.php line 38: Trying to get property of non-object

### ISSUE THREAD

**Issue by Habilya** [jcc/blog#35]
error when trying not existent tag or category 
exemple 

/category/111111111111111111111111111

/tag/111111111111111111

$articles = $this->category->getByName($category)->articles;

$tag = $this->tag->getByName($tag);

**Comment by Habilya** [comment]
should return 404

**Comment by jcc** [comment]
I fixed it in the latest version. [https://github.com/jcc/blog/tree/v1.1.10](https://github.com/jcc/blog/tree/v1.1.10) #
