### ISSUE TITLE
新建article一直不成功，报301

### ISSUE THREAD

**Issue by AndyxingY** [jcc/blog#39]
<img width="470" alt="screen shot 2017-04-13 at 12 31 11 pm" src="https://cloud.githubusercontent.com/assets/21179164/24990344/df0627fe-2045-11e7-930f-e5e3a82de29b.png">
<img width="460" alt="screen shot 2017-04-13 at 12 30 55 pm" src="https://cloud.githubusercontent.com/assets/21179164/24990345/e6af3e32-2045-11e7-8649-09770d49f61d.png">
article的post，报301，然后重定向到了get，一直创建不了文章，请问是什么原因呢？麻烦大牛了，谢谢。

**Comment by jcc** [comment]
请看一下 `laravel.log`

**Comment by AndyxingY** [comment]
Log里边没有报错，是空的，请问是什么原因呢？好诡异呀，别的都可以新建，就文章新建不了。

**Comment by jcc** [comment]
看一下 post 的 api 的 response 有没有返回数据。

**Comment by AndyxingY** [comment]
console了response发现里边的是get返回的数据。
<img width="750" alt="screen shot 2017-04-13 at 1 03 48 pm" src="https://cloud.githubusercontent.com/assets/21179164/24990882/aaa8ba68-2049-11e7-93ad-5ab1e60a1975.png">
事实上，我已经注释掉回调了，但是submit就会产生两个请求，一个post(301)，一个get（response里的数据就是get的）

**Comment by jcc** [comment]
我无法复现你所说的
