### ISSUE TITLE
500 Base table or view not found: 1146 Table 'votables' doesn't exist 

### ISSUE THREAD

**Issue by Habilya** [jcc/blog#41]
I believe I missed something?
or there is something missing in the migration?

Please advice.

**Comment by jcc** [comment]
You try to run the command of `composer update laravel-vote -vvv`. I fixed the bug with the [Laravel Vote](https://github.com/jcc/laravel-vote)

**Comment by Habilya** [comment]
Still getting this error..

**Comment by Habilya** [comment]
I don't know what's **votables** I've searcheed whole project for that word, but couldn't find it..

**Comment by jcc** [comment]
Had you been running the command `php artisan migrate`? I add the vote feature for comments.

**Comment by Habilya** [comment]
Yes it creates table **votes** not **votables**.

**Comment by jcc** [comment]
Still getting that error?

**Comment by Habilya** [comment]
yes error is still there. 
I will be going through the files I have merged from your repo, maybe I made a mistake when I was merging...

**Comment by jcc** [comment]
@Habilya Ok, you need to delete the `composer.lock` file. And then you re-run the `composer install -vvv` command.

**Comment by Habilya** [comment]
Ok, I reviewed my files that I have merged.
I think you need to add a migration for **votables** table

$this->morphToMany($property, 'votable');
$this->morphedByMany($this->voteRelation, 'votable', 'votes')->withTimestamps();

You reference **votable** in the code

**Comment by jcc** [comment]
I add the tag of v1.0.1. And then I deleted the tag, so you installed the v1.0.1 when you ran `composer install`

**Comment by lb308** [comment]
Hi thanks Mr.Jcc for this blog
I try to add an article and it not create in the DB and also I try to comment in articles or dissc and nothing words 
thanks

**Comment by jcc** [comment]
@Habilya @lb308 Update the latest code.
