### ISSUE TITLE
Adding new article not working?

### ISSUE THREAD

**Issue by lb308** [jcc/blog#43]
I try to add a new article but nothing happen the database is empty and the list of article also showing nothing.. U guess something related to the post method in the Form Article 

`        onSubmit() {
            if (!this.tags || !this.selected) {
                toastr.error('Category and Tag must select one or more.')
                return;
            }

            let tagIDs = []
            let url = 'article/' + (this.article.id || '')
            let method = (this.mode == 'update') ? 'patch' : 'post'

            for(var i = 0 ; i < this.tags.length ; i++) {
                tagIDs[i] = this.tags[i].id
            }

            this.article.published_at = this.startTime.time
            this.article.content = this.simplemde.value()
            this.article.category_id = this.selected.id
            this.article.tags = JSON.stringify(tagIDs)

            this.$http[method](url, this.article)
                    .then((response) => {
                        toastr.success('You ' + this.mode + 'd the article success!')

                        this.$router.push('/dashboard/articles')
                    }).catch(({response}) => {
                        stack_error(response.data)
                    })
        },
`

thanks

I use windows 10 + local Xampp server.

**Comment by jcc** [comment]
I can not reproduce your problem. Please check the log.

**Comment by lb308** [comment]
hi, I think the post request in the article form not working for me. this is a video show you that when I edit an article the Patch request works fine, but when I create a new article the post request not works and nothing saved in the Article Table DB..


https://www.youtube.com/watch?v=P7qg75ll7og

**Comment by jcc** [comment]
The video can not play.

**Comment by lb308** [comment]
try now ..sorry it was private now its public

**Comment by jcc** [comment]
@lb308 You try to move the `/` before `this.article.id` or you try to delete `/` when you create article.

```js
let url = 'article**/**' + (this.article.id || '')
```

I can't reproduce the problem.

**Comment by lb308** [comment]
thank you.
I just install fresh blog and try to add a new article after I use composer blog:install ...
the problem is when I try to add the new article 
other are all fine 


thanks

**Comment by jcc** [comment]
@lb308 I think this problem may be caused by the apache `.htaccess` file. You can see these articles.
[https://mdk.fr/blog/post-data-lost-on-301-moved-permanently.html](https://mdk.fr/blog/post-data-lost-on-301-moved-permanently.html)
[http://stackoverflow.com/questions/35565809/can-not-post-in-laravel-5-over-jquery-ajax](http://stackoverflow.com/questions/35565809/can-not-post-in-laravel-5-over-jquery-ajax)

**Comment by jcc** [comment]
@lb308 Ok, you try to pull the latest code with master branch. Then compile the frontend code.

**Comment by lb308** [comment]
thanks a lot now it works great.
