### ISSUE TITLE
editing the discussion item return an error 

### ISSUE THREAD

**Issue by lb308** [jcc/blog#45]
hi hope you doing well,

I try to edit a discussion and I get this error : 

`Argument 1 passed to App\Repositories\DiscussionRepository::update() must be an instance of App\Repositories\int, string given, called in C:\xampp\htdocs\blog\app\Http\Controllers\DiscussionController.php on line 121 and defined`

both side from dashboard and also from the homepage...

the discussionRepository code : 

```php
    /**
     * Update a record by id.
     * 
     * @param  int $id
     * @param  array $data
     * @return boolean
     */
    public function update($id, $data)
    {
        $this->model = $this->checkAuthScope();

        $discussion = $this->model->findOrFail($id);

        if (is_array($data['tags'])) {
            $this->syncTag($discussion, $data['tags']);
        } else {
            $this->syncTag($discussion, json_decode($data['tags']));
        }

        return $discussion->update($data);
    }
````

**Comment by jcc** [comment]
@lb308 You can try pull the latest code with the master branch.

**Comment by lb308** [comment]
thanks for reply I did it again with new fresh copy code and here is the video
https://www.youtube.com/watch?v=1ceO3bMzlGs

the seam error

👍

**Comment by jcc** [comment]
I can't re-product the error. Can you show the error in detail？

**Comment by lb308** [comment]
Fixed 👍 I just update my server Xampp to PHP Version 7.1.1
last version with php 7

thanks

**Comment by lb308** [comment]
here it is a nice debuger bar for Laravel : https://github.com/barryvdh/laravel-debugbar
thanks again

**Comment by lb308** [comment]
Hi again, I have a question, how can I add a localization to the blog switch languages, and how to add the like system or vote to the articles so the most liked article will be the first article on top of the lists..
thank you so much

**Comment by jcc** [comment]
- You can add a new language to `resources/lang`, and then switch in `config/app.php`.
- You can refer to comments on how to finish the feature of vote.

**Comment by lb308** [comment]
thanks a lot 👍
