### ISSUE TITLE
Vote system needs a helper HasVotedType

### ISSUE THREAD

**Issue by Habilya** [jcc/blog#50]
Right now, you can only know if user has voted  by **is_voted**, in the comment.vue

Need also something like **is_voted_type** to know what kind of vote was that, Down or Up.

**Comment by Habilya** [comment]
It in CommentTransformer.php

**Comment by jcc** [comment]
@Habilya You can use the methods of `hasUpVoted()` and `hasDownVoted()`

**Comment by Habilya** [comment]
in CommentTransformer.php

add 

'is_up_voted'      => auth()->guard('api')->id() ? $comment->hasUpVoted(auth()->guard('api')->id()) : false,
'is_down_voted'      => auth()->guard('api')->id() ? $comment->hasDownVoted(auth()->guard('api')->id()) : false,

?

**Comment by Habilya** [comment]
or even just
`'is_up_voted' => auth()->guard('api')->id() ? $comment->hasUpVoted(auth()->guard('api')->id()) : false,`

If it is   `is_voted` and not `is_up_voted` logically it is a down vote.....
?

**Comment by jcc** [comment]
No.

```php
'is_voting' => auth()->guard('api')->id() ? auth()->guard('api')->hasUpVoted($comment) : false,
'is_down_voting' => auth()->guard('api')->id() ? auth()->guard('api')->hasDownVoted($comment) : false,
```

Determine the comment whether the vote has been by current user. And then only the following happens : 

```php
is_voting = true
is_down_voting = false

// Or

is_voting = false
is_down_voting = true

// Or

is_voting = false
is_down_voting = false
```

**Comment by Habilya** [comment]
ok thank you, will do it in 8 hours (Im at work now don't have access to my IDE)

**Comment by Habilya** [comment]
Ok I'm setting up my IDE and git to work with my FORK

Will PR this week, I changed the icons of thumbs to arrows, and made them color only if user did the action
- Up arrow is green if UpVoted
- Down arrow is red if DownVoted
- No vote arrows system color
- I still display negative votes, ex: -1 -2 -... (Red if <0 Green if > 0)

You can review and change the design after i PR.

**Comment by jcc** [comment]
@Habilya OK 👌

**Comment by Habilya** [comment]
Sorry it took too long, I had to merge ALL your commits with my personal blog repository first....
You did a lot of things since last time I merged

**Comment by jcc** [comment]
@Habilya Yes. You pr after you solve the conflict.

**Comment by lb308** [comment]
hi dear, How can we make just one notification (make as read) after I click on this notification ...one by one

**Comment by jcc** [comment]
@lb308 Ok，I will finish the feature in the next version.
