### ISSUE TITLE
SEO ?

### ISSUE THREAD

**Issue by Habilya** [jcc/blog#53]
Maybe a good practice to think about some issues with SEO

Here is **HTMLImprovements** report from google webmasters tools search console
about the blog
![2017-04-24 15-40-46](https://cloud.githubusercontent.com/assets/26153731/25355600/2dc99dcc-2905-11e7-872d-e5ad14f61bf0.jpg)

Maybe we could use the articles Meta description as page metadescription
and article tags as title tags

Also Search Engines "like" when every page have **1**  `<h1>`

**Comment by jcc** [comment]
I think this requires the user to optimize by themselves.
