### ISSUE TITLE
Discussion Comment if the status is false

### ISSUE THREAD

**Issue by lb308** [jcc/blog#54]
Hi, thank you for this awesome blog.
my issue is when I make the discussion status off, I still can comment and I get a alert that the comment is disabled...

https://www.youtube.com/watch?v=EYimD-PBN9c

my fix for that is to check if the status is = 0 then I show just the comment without the textaria, and if = 1 I show normal comment for all guest and user..

my code : 

`@if($discussion->status == 0)`
`             <comment commentable-type="discussions"`
`                    commentable-id="{{ $discussion->id }}"`
`                     null-text="dfasdf"></comment>`
`    @else`
`        @if(Auth::guest())`
`            <comment commentable-type="discussions"`
`                    commentable-id="{{ $discussion->id }}"`
`                    null-text=""></comment>`
`        @else`
`            <comment username="{{ Auth::user()->name }}"`
`                     user-avatar="{{ Auth::user()->avatar }}"`
`                     commentable-type="discussions"`
`                     commentable-id="{{ $discussion->id }}"`
`                     null-text=""`
`                     can-comment></comment>`
`        @endif`
`    @endif`

**Comment by Habilya** [comment]
You are admin, admin can see (and edit?) the Links,Discussions,Articles outside of normal user scope.

Try the same with normal user, it wont work...

**Comment by lb308** [comment]
thanks Habilya, yes I can't see the discu with normal user, that is good 👍   fixed thanks
