### ISSUE TITLE
creating article issue

### ISSUE THREAD

**Issue by m2ura** [jcc/blog#56]
I have an issue with creating an article update, every time I try to create an article it doesn't get created or posted and  i get this using the latest code updates.

![article](https://cloud.githubusercontent.com/assets/13012135/25457728/8c152cf6-2ad7-11e7-858c-14b1bca70831.png)

**Comment by jcc** [comment]
@m2ura Did you have an error message?

**Comment by m2ura** [comment]
No error message but it doesn't post anything

**Comment by lb308** [comment]
which PHP version you use ? you have to use PHP version 7.0 and up

**Comment by m2ura** [comment]
Yes it's PHP7

**Comment by m2ura** [comment]
@lb308 Thank you, all working now.

**Comment by jcc** [comment]
@m2ura Sorry, I can not reproduce your problem. What is the problem?

**Comment by m2ura** [comment]
@jcc It's solved now :+1:

**Comment by lb308** [comment]
good to hear. but can you tell us how did you solve it? so next time if someone face the same problem we can answer him easily.

thanks

**Comment by m2ura** [comment]
@lb308 I forgot to run 'npm run dev' command.
