### ISSUE TITLE
文章内容中出现"、&quot;、&#34;文章最终页面解析有问题

### ISSUE THREAD

**Issue by luyuqiang** [jcc/blog#58]

**Comment by jcc** [comment]
@luyuqiang 你所指的解析问题是直接转义了？

**Comment by luyuqiang** [comment]
我通过搜索引擎发现有人遇到了类似的问题，https://laravel-china.org/articles/3517/finally-came-combined-with-laravel-53-vue-21-component-of-the-development-of-the-blog-system
文中提到：
“这里的 $article->content 里面的内容在文本编辑器编辑的时候不要包含 "" ->英文状态下的双引号，不然会报错，提醒下大家～”

这个问题没有解决办法吗？

**Comment by jcc** [comment]
@luyuqiang 你是在文本编辑器输入了什么内容才会出现错误的，我本地没有试出来

**Comment by luyuqiang** [comment]
输入英文的双引号 " 和 反引号 `
都会有问题。
我给出一个我博客的地址吧
双引号问题：https://www.luyuqiang.com/php-wiki
反引号问题：https://www.luyuqiang.com/php-call-system-command
不知道什么原因

**Comment by jcc** [comment]
能给一下你 `markdown` 输入的内容吗？

**Comment by luyuqiang** [comment]
英文双引号内容是 "
反引号问题内容是是 ``
就是以上内容。
你本地不会出问题吗？难道是我部署的时候有问题？

**Comment by jcc** [comment]
反引号是一种 `markdown` 语法

**Comment by luyuqiang** [comment]
不过我发现可以用 \\\+` 页面显示就是 期待的反引号啦

**Comment by jcc** [comment]
@luyuqiang 好的，我迟点再看看，我直接用英文双引号没问题喔。

**Comment by jcc** [comment]
@luyuqiang 我找人测了一下也没出现这种情况
