### ISSUE TITLE
Upload Avatar Fail (Image source not readable)

### ISSUE THREAD

**Issue by shern91** [jcc/blog#60]
When I try to upload my avatar(.jpg), I get 
`Failed to load resource: the server responded with a status of 404 (Not Found)`

After Click "确 定" button, I check the F12 on chrome, 500 error,  
`Uncaught (in promise) Error: Request failed with status code 500` (Image source not readable)
![avatar1](https://cloud.githubusercontent.com/assets/16183843/26719175/113d2c8a-47b6-11e7-9843-000b5f745ce6.png)
![avatar2](https://cloud.githubusercontent.com/assets/16183843/26719176/116db530-47b6-11e7-8db0-b91cebe217c7.png)

**Comment by jcc** [comment]
Please try to run the command of `php artisan storage:link`

**Comment by shern91** [comment]
Thanks for your quick response, I run the `php artisan storage:link`, still get the same error.

**Comment by jcc** [comment]
@shern91 You could not preview the image after uploading. I think you can't access the picture normally. First, you find the directory of `public/storage`. If you can not see your uploaded image that you need soft connection `storage/app/public` to `public/storage`.

**Comment by shern91** [comment]
@jcc After i chose my image, the "确 定" button is not working, I press several times, the "Crop Avatar" Modal is not closing, i think my image wasn't upload successful.

**Comment by jcc** [comment]
Can you see the laravel.log and then show me the detail error? The upload action is triggered when you select the image. And then it will show the crop modal for you to crop your uploaded image.

**Comment by shern91** [comment]
@jcc my laravel.log file doesn't exists. In my storage/logs, only have .gitignore file.

**Comment by jcc** [comment]
Sorry, I don't know more about your problem and I can't reappear the problem.

**Comment by shern91** [comment]
@jcc, it's ok, I try fix first, because all the error i got i already provide. 不好意思，我之前还可以upload的，因为很久没开，昨天开来看看，就不能上载了，我也试过git pull origin master, composer install & npm install再试，还是得到一样error.

**Comment by jcc** [comment]
你之前的是什么版本？没有错误信息我定位不了问题。

**Comment by shern91** [comment]
之前也是5.4版本的，昨天git pull之前是有19个新的commit的，其实楼主的这个blog还蛮难的，很多我都看不懂，还在学习，我想建立自己的blog，有些upload照片的功能，所以就借来参考参考一下.

**Comment by jcc** [comment]
@shern91 容易你就不会去学了，加我 QQ 吧。完全不知道你的是什么问题。

**Comment by shern91** [comment]
@jcc 谢谢你的邀请，不过我没玩QQ耶，我尽量放上我的error，以下的图片是我在chrome的inspection拿到的，我在的logs folder里面没有laravel.log文件

![4](https://cloud.githubusercontent.com/assets/16183843/26734251/f15102f4-47ef-11e7-8b02-f55a7648ae6e.png)

![5](https://cloud.githubusercontent.com/assets/16183843/26734252/f156658c-47ef-11e7-8503-9b6d772075c2.png)

![6](https://cloud.githubusercontent.com/assets/16183843/26734253/f16daba2-47ef-11e7-84f3-4fb03c212e78.png)

**Comment by jcc** [comment]
看报错，连图片都找不到，证明没有获取到图片，你确定一下 `public/storage` 下是否有图片文件

**Comment by shern91** [comment]
@jcc 没有，我要找不到upload照片的function，因为好像不是写在controller的，我对Vue还不是很了解，希望大大可以指教一些

**Comment by jcc** [comment]
证明你没有软连接成功，你只需将 `storage/app/public` 软连接到 `public/storage` 正是我上面要你输入的命令！[comment](https://github.com/jcc/blog/issues/60#issuecomment-305739110)

**Comment by shern91** [comment]
@jcc command 我run了，
`Cannot create a file when that file already exists.
The [public/storage] directory has been linked.`

然后我去把database里的path直接换去已经存在的照片的path，就是＋ app/public/ 在storage 之后，还是显示不到头像

**Comment by jcc** [comment]
你删了 `public/storage` 后重新运行一下吧。

**Comment by shern91** [comment]
`public/storage` 还是 `storage/app/public` ?

**Comment by jcc** [comment]
`public/storage` 吖。看清楚我发的信息！

**Comment by shern91** [comment]
@jcc 不好意思哦，因为我 public folder里没有这个folder，所以我才要确定一下

**Comment by jcc** [comment]
@shern91 就是因为软连接的问题了。你是使用什么环境的？

**Comment by shern91** [comment]
@jcc windows10, 直接在 http://127.0.0.1:8000/ 运行

**Comment by jcc** [comment]
@shern91 请你先解决软连接问题。
