### ISSUE TITLE
关于权限问题

### ISSUE THREAD

**Issue by wh469012917** [jcc/blog#69]
在`storage/oauth-public.key`这个文件的作用是什么？一直报错说权限问题，查看了源码该权限必须是600，于是给了600之后又报错说该文件不存在或者不可读。文件确确实实是存在的，权限必须是600，现在又报错不可读，这种矛盾bug如何解决？

**Comment by jcc** [comment]
- [https://stackoverflow.com/questions/39414956/laravel-passport-key-path-oauth-public-key-does-not-exist-or-is-not-readable](https://stackoverflow.com/questions/39414956/laravel-passport-key-path-oauth-public-key-does-not-exist-or-is-not-readable)
- [https://github.com/laravel/passport/issues/418](https://github.com/laravel/passport/issues/418)

遇到非程序问题，请先自行 Google 解决。效率比你现在要高 N 倍。
