### ISSUE TITLE
No database selected issues.

### ISSUE THREAD

**Issue by jjljyn** [jcc/blog#7]
if I run *php artisan blog:install*, I got some massages following.

php artisan key:generate
Application key [base64:cDeboONQP5eHhkErNlhyVfqCzHyWL/9SltOcJFSnZbQ=] set successfully.

---
---
php artisan migrate --seed

  [Illuminate\Database\QueryException]
  SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected (SQL: create table `migrations` (`id` int unsign
  ed not null auto_increment primary key, `migration` varchar(255) not null, `batch` int not null) default character set utf8 collate utf8_unicode_ci)

  [PDOException]
  SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected

---
---
php artisan passport:install
Encryption keys generated successfully.

  [Illuminate\Database\QueryException]
  SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected (SQL: insert into `oauth_clients` (`user_id`, `n
  ame`, `secret`, `redirect`, `personal_access_client`, `password_client`, `revoked`, `updated_at`, `created_at`) values (, PJ Blog Personal Access Client, QfMFsu6SGodoThaVinX8rTLS7K7nQbZNVqM94q9B, http://localhost, 1, 0, 0, 201
  7-01-08 16:41:50, 2017-01-08 16:41:50))

  [PDOException]
  SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected

---

And .env file like this:

> APP_ENV=local
APP_KEY=base64:cDeboONQP5eHhkErNlhyVfqCzHyWL/9SltOcJFSnZbQ=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://localhost

> DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=
DB_USERNAME=
DB_PASSWORD=

**Comment by jcc** [comment]
You must set the database's configurations in the file of the `.env`. And then you should create the a new database for the configuration of `DB_DATABASE`.

**Comment by ownsupernoob2** [comment]
is this blog using MySQL? please answer
