### ISSUE TITLE
关于文章content字段长度的探讨

### ISSUE THREAD

**Issue by wh469012917** [jcc/blog#70]
如题，文章content字段是text类型，长度为65535，但是存储了raw和html，也就是说实际存储了两倍的内容，假如文章长度很长呢？
其实正常情况下text够用了，但是我在迁移自己wordpress博客的时候就出现了这个问题，有一篇超长文章，插入的时候直接抛出异常了。
所以，请教下是否有必要更改为mediumtext类型？

**Comment by jcc** [comment]
@wh469012917 按照你实际需求来调整，下一版本会考虑将这 2 个字段分开.
