### ISSUE TITLE
后台文件上传bug

### ISSUE THREAD

**Issue by wh469012917** [jcc/blog#71]
后台文件上传的时候，如果使用第三方存储（七牛云，又拍云），会有一个很严重的bug，看代码：
```php
return [
                'success' => true,
                'filename' => $hashName,
                'original_name' => $file->getClientOriginalName(),
                'mime' => $mime,
                'size' => human_filesize($file->getClientSize()),
                'real_path' => $realPath,
                'relative_url' => "storage/$realPath",
                'url' => $this->disk->url($realPath),
        ];
```
这是上传后返回的数据，这里写死了返回的url，这样在使用非public磁盘的时候，会生成错误的地址的。应该这样修改：
```
 'relative_url' => $this->disk->url($realPath),
```
通过Storage类里面的url方法来生成才对。

这里还有一些建议：
1.后台图片没有上传进度，没有错误处理，体验很不好，建议这里可以修改下。
2.数据库中对于json类型的字段，可以使用laravel自带的数据类型转换来，举例子：

对于Article模型,可以定义一个这样的属性：
```php
protected $casts = [
    'content'    =>    'array'
];
```

然后前台就可以这样调用：
```php
$article->content['raw']
```

虽然效果一样，但是比原先通过`json_decode($article->content)->raw`这样好多了

**Comment by jcc** [comment]
@wh469012917 文件上传以及建议的第二点可以提个 pr 给我么？第一点暂不考虑

**Comment by jcc** [comment]
@wh469012917 回头想了想，使用第三方的存储，应该重写一下 `BaseManager` 而不是直接使用，又拍云已支持。

**Comment by wh469012917** [comment]
@jcc 看了下，好像你并没有直传到第三方存储，都是到服务器了，然后服务器再到云存储。这样的话直接拓展一块磁盘即可了，感觉用BaseManager有点画蛇添足。

**Comment by jcc** [comment]
@wh469012917 主要用于返回数据格式。第三方存储你可以看看我重写了一个 UpyunManager
