### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'blog.oauth_clients' doesn't exist

### ISSUE THREAD

**Issue by alipeng** [jcc/blog#78]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'blog.oauth_clients' doesn't exist

**Comment by alipeng** [comment]
数据库迁移时出现以下错误
```
[PDOException]                                                                                                   
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes 
```
解决方案[https://stackoverflow.com/questions/23786359/laravel-migration-unique-key-is-too-long-even-if-specified](https://stackoverflow.com/questions/23786359/laravel-migration-unique-key-is-too-long-even-if-specified)
@jcc 修复以下

**Comment by jcc** [comment]
你也可以将 mysql 升级到 5.7

**Comment by alipeng** [comment]
我用的是MariaDB 10.1.26
