### ISSUE TITLE
npm 问题

### ISSUE THREAD

**Issue by lufeijun** [jcc/blog#80]
npm install 时，一直卡在 / extract:fsevents: sill pacote fsevents@https://registry这，请问是镜像问题么

**Comment by jcc** [comment]
@lufeijun 尝试一下删除 `node_modules` 后重新安装一下，或者使用 `yarn` 代替 `npm`

**Comment by lufeijun** [comment]
OK。我试试，谢谢






在 2017-10-09 17:12:53，"Jiajian Chan" <notifications@github.com> 写道：


@lufeijun 尝试一下删除 node_modules 后重新安装一下，或者使用 yarn 代替 npm
