### ISSUE TITLE
404 /login

### ISSUE THREAD

**Issue by zurafatihah** [jcc/blog#85]
I have managed to install and running but when I go to login/register page it says : The requested URL /login was not found on this server.

**Comment by jcc** [comment]
Have you set the nginx config for rewrite route？
[https://laravel.com/docs/5.5#web-server-configuration](https://laravel.com/docs/5.5#web-server-configuration)

**Comment by zurafatihah** [comment]
I use apache running on CentOS 7

**Comment by jcc** [comment]
emmm.... Have you switched on the `mod_rewrite`?

**Comment by zurafatihah** [comment]
AFAIK is to change <Directory /var/www/html> section and change the directive from None to All, is that right?

my web is http://5s5t.com/ maybe you can take a look

**Comment by zurafatihah** [comment]
I believe I've already enable `mod_rewrite` and restart apache server but still the same, the only working is navigation pagination number to next page article other than that always 404.

**Comment by jcc** [comment]
@zurafatihah Sorry, I don't konw now. I didn't use apache but I see someone using apache2 normal operation.

**Comment by zurafatihah** [comment]
Now I can confirm I've got it working with nginx, another thing I want to ask. When I try to create tag for article its only allow me to enter 1 character, how can I fix this?

**Comment by jcc** [comment]
You can edit the [vue file](https://github.com/jcc/blog/blob/master/resources/assets/js/views/dashboard/article/Form.vue#L55-L67) . And then you can reference the [category input](https://github.com/jcc/blog/blob/master/resources/assets/js/views/dashboard/article/Form.vue#L8-L14). 

Finally, you must remeber to run the command of `npm run dev(or watch/prod)`.

**Comment by zurafatihah** [comment]
Ahhhh thanks, one last thing on footer icon it only had Home, Github and Twitter. Can I add more like Facebook and other custom link?

**Comment by jcc** [comment]
Yes, you can add what you want.

**Comment by zurafatihah** [comment]
Thanks, can you guide me where is the file located?
