### ISSUE TITLE
Cantered Image In Article Content

### ISSUE THREAD

**Issue by dsrukmana** [jcc/blog#86]
Thanks for your beautiful blog it's awesome, however I'm not able to get image position into center when adding into article. I've looking into manual but couldn't find, and Also I want to add Facebook link with icon onto footer, can you tell me how to do this?

**Comment by jcc** [comment]
You can add links what you want in this [file](https://github.com/jcc/blog/blob/master/resources/views/particals/footer.blade.php).  If you want to  get image position into center, you can set image position into center in [styles.scss](https://github.com/jcc/blog/blob/master/resources/assets/sass/styles.scss). Remember to compile the front code.

**Comment by dsrukmana** [comment]
So after add class manually for image postion I need compile again with "npm run dev/watch/production" ?

**Comment by jcc** [comment]
yes

**Comment by dsrukmana** [comment]
Ok thanks, I think I just fix it 👍
