### ISSUE TITLE
vue-cli  spa  这种 文件按需加载 是否可以实现的呢 ？

### ISSUE THREAD

**Issue by jxZhangLi** [jcc/blog#90]

**Comment by jcc** [comment]
vue 的文件按需加载？后台的页面有的。

**Comment by jxZhangLi** [comment]
那其实 ,像前台页面 就像 vue-server-renderer 这样，首屏渲染的这种意思是吧。

**Comment by jcc** [comment]
前台页面是直接用 blade 模板，并不是 vue 单页

**Comment by jxZhangLi** [comment]
我明白,那我下载的项目，是没有带后台的吧，我怎么进不去勒

**Comment by jcc** [comment]
看手册吧，[https://manual.pigjian.com](https://manual.pigjian.com)，可能是因为你用户不是管理员。

**Comment by jxZhangLi** [comment]
![image](https://user-images.githubusercontent.com/16809535/34862162-e20d0d42-f7a3-11e7-8a85-0e35ed9de4a5.png)
你看我这里怎么运行不起来呀
