### ISSUE TITLE
Error: Request failed with status code 500 	  

### ISSUE THREAD

**Issue by xushaobo** [jcc/blog#92]
when press the create button
error shows:
Error: Request failed with status code 500 	
app.js?...b3973ec (line 678, col 15)

**Comment by jcc** [comment]
Please follow up the file of `laravel.log`

**Comment by xushaobo** [comment]
sorry, the log shows:
local.ERROR: chmod(/www/wwwroot/manbofish.com/storage/oauth-public.key): Operation failed: Operation not permitted {"exception":"[object] (ErrorException(code: 0): chmod(/www/wwwroot/manbofish.com/storage/oauth-public.key): Operation failed: Operation not permitted at /www/wwwroot/manbofish.com/vendor/league/oauth2-server/src/CryptKey.php:51)
[stacktrace]

I try the method from stackoverflow 
:sudo chown www-data:www-data storage/oauth-*.key
sudo chmod 600 storage/oauth-*.key
but can't solve my problem

**Comment by jcc** [comment]
You try to run the command of `php artisan passport:install`

**Comment by xushaobo** [comment]
the result is:
Encryption keys already exist. Use the --force option to overwrite them.
Personal access client created successfully.
Client ID: 5
Client Secret: DLRf5H3NHA007K3Zl4IkE7mGqgPaEmQ2Do34OPBe
Password grant client created successfully.
Client ID: 6
Client Secret: ypDLFoX3kkkLONknh2Kb2EgQqjiEPBZcEF9FkHlc

laravel.log:
[2018-01-14 12:52:50] local.ERROR: chmod(/www/wwwroot/manbofish.com/storage/oauth-public.key): Operation failed: Operation not permitted {"exception":"[object] (ErrorException(code: 0): chmod(/www/wwwroot/manbofish.com/storage/oauth-public.key): Operation failed: Operation not permitted at /www/wwwroot/manbofish.com/vendor/league/oauth2-server/src/CryptKey.php:51)

any help!

**Comment by xushaobo** [comment]
After update the passport package the application runs fine,Thanks!
The command:
6.xcomposer.json
"laravel/passport": "^3.0"
composer update
