### ISSUE TITLE
Question about cleaning inputs

### ISSUE THREAD

**Issue by j574144** [jcc/blog#94]
HI, firstly I want to congrat for great work. 

About cleaning input (on markdown editor), wath your have implemented on this blog?.

Thanks for your answer.

**Comment by jcc** [comment]
About cleaning input? Can you describe it in detail?

**Comment by j574144** [comment]
Hi, thanks for your answer. 

This is about HTML sanitization to prevent XSS attacks

https://en.wikipedia.org/wiki/HTML_sanitization

**Comment by jcc** [comment]
Because I saved the markdown format data. And then I use the `marked.js` to render the content. Can't output the html content.

**Comment by j574144** [comment]
I not understand completely how does marked.js  played to prevent XSS attack, so if you put ```<a onmouseover=alert(document.cookie)>click me!</a>``` on new blog input or comment, this generate the alert with info.

The idea about prevent XSS attack is filter this specific tags or statement. 

Refered info: https://blog.sqreen.io/xss-in-vue-js/ 
Thanks.

**Comment by jcc** [comment]
Oh, I'm very sorry. I had not dealt with this issue yet. I will dealt with it after I upgrade bootstrap 3 to 4 version.

**Comment by jcc** [comment]
@j574144 Of course, you can also pull requests for this.

**Comment by jcc** [comment]
@j574144 You can try to use  the upgrade branch.

**Comment by j574144** [comment]
This is great approach to resolve it, but still is necessary adjust some parameters of purifier,  because after apply it the output  is not what was expected.

Thanks for your contribution and support.

**Comment by j574144** [comment]
@jcc recently I asked you about purify html and you have implemented Mews\Purifier, but this have some problems with output. 

I only want to refer that if you are using marked, you can enable [sanitize](https://github.com/chjj/marked#sanitize) and this have very behaivor and the output is best. 

I hope will be help it...

**Comment by jcc** [comment]
@j574144 That's great. Emmmm....I did not think about this issue from the front-end level. And I will remove the package of the Mews\Purifier. Thank you for your supports.
